---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/28/2021 9:38 PM
---

ErmMarsPeople = {}

require('__erm_marspeople__/global')
require('util')

local ErmConfig = require('__enemyracemanager__/lib/global_config')

local ERM_WeaponRig = require('__enemyracemanager__/lib/rig/weapon')

data:extend(
        {
            {
                type = "ammo-category",
                name = "marspeople-damage"
            },
        })

require "prototypes.projectiles"
require "prototypes.building.lab"
require "prototypes.enemy.miniufo"
require "prototypes.enemy.marspeople"
require "prototypes.enemy.marspeople-fire"
require "prototypes.enemy.marspeople-icy"

local level = ErmConfig.MAX_LEVELS

for i = 1, level do
    --Units
    ErmMarsPeople.make_miniufo(i)
    ErmMarsPeople.make_marspeople(i)
    ErmMarsPeople.make_marspeople_fire(i)
    ErmMarsPeople.make_marspeople_icy(i)

    --Building
    ErmMarsPeople.make_lab(i)
end

