---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/23/2020 8:27 PM
---

local String = require('__stdlib__/stdlib/utils/string')
local Math = require('__stdlib__/stdlib/utils/math')
local Table = require('__stdlib__/stdlib/utils/table')

local ForceHelper = require('__enemyracemanager__/lib/helper/force_helper')
local CustomAttackHelper = require('__enemyracemanager__/lib/helper/custom_attack_helper')

local droppable_unit_name = {
    { 'marspeople', 'miniufo' },
    { 'marspeople', 'marspeople-icy', 'miniufo', 'eye-ufo-a' },
    { 'marspeople', 'marspeople-icy', 'marspeople-fire', 'ufo', 'miniufo', 'eye-ufo-a', 'eye-ufo-b' },
}
local get_droppable_unit = function()
    return CustomAttackHelper.get_unit(droppable_unit_name, MOD_NAME)
end

local probe_building_name = {
    { 'shortrange-laser-turret' },
    { 'shortrange-laser-turret' },
    { 'shortrange-laser-turret', 'exit_en', 'exit_jp' },
}
local get_buildable_structures = function()
    return CustomAttackHelper.get_unit(probe_building_name, MOD_NAME)
end

local CustomAttacks = {}

CustomAttacks.valid = CustomAttackHelper.valid

function CustomAttacks.process_builder(event)
    CustomAttackHelper.drop_unit(event, MOD_NAME, get_buildable_structures())
    event.source_entity.die('neutral')
end

function CustomAttacks.process_dropship(event)
    CustomAttackHelper.drop_unit(event, MOD_NAME, get_droppable_unit())
end

return CustomAttacks