---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/6/2021 2:07 PM
---

require("util")
local Sprites = require('__stdlib__/stdlib/data/modules/sprites')
local fireutil = require('__base__/prototypes/fire-util')
local sounds = require('__base__/prototypes/entity/sounds')
local math3d = require "math3d"

local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
local ERMDataHelper = require('__enemyracemanager__/lib/rig/data_helper')

local marspeople_beams = util.table.deepcopy(data.raw['beam']['laser-beam'])
marspeople_beams.name = MOD_NAME.."/marspeople-laser-beam"
marspeople_beams.head.tint = ERM_UnitTint.tint_green()
marspeople_beams.tail.tint = ERM_UnitTint.tint_green()
marspeople_beams.body[1].tint = ERM_UnitTint.tint_green()
if marspeople_beams.light_animations then
    marspeople_beams.light_animations.head.tint = ERM_UnitTint.tint_green()
    marspeople_beams.light_animations.tail.tint = ERM_UnitTint.tint_green()
    marspeople_beams.light_animations.body[1].tint = ERM_UnitTint.tint_green()
end

if marspeople_beams.ground_light_animations then
    marspeople_beams.ground_light_animations.head.tint = ERM_UnitTint.tint_green()
    marspeople_beams.ground_light_animations.tail.tint = ERM_UnitTint.tint_green()
    marspeople_beams.ground_light_animations.body.tint = ERM_UnitTint.tint_green()
end

data:extend({
    ------- Laser Beam -----
    marspeople_beams,
    ------- Fire -------
    fireutil.add_basic_fire_graphics_and_effects_definitions(
            {
                type = "fire",
                name = MOD_NAME.."/fire-flame",
                flags = { "placeable-off-grid", "not-on-map" },
                damage_per_tick = { amount = 4 / defines.time.second, type = "fire" },
                maximum_damage_multiplier = 3,
                damage_multiplier_increase_per_added_fuel = 1,
                damage_multiplier_decrease_per_tick = 0.005,

                spawn_entity = "fire-flame-on-tree",

                spread_delay = 300,
                spread_delay_deviation = 180,
                maximum_spread_count = 100,

                emissions_per_second = 0.005,

                initial_lifetime = 300,
                lifetime_increase_by = 150,
                lifetime_increase_cooldown = 4,
                maximum_lifetime = 600,
                delay_between_initial_flames = 10,
                --initial_flame_count = 1,
            }),
    {
        type = "sticker",
        name = MOD_NAME.."/fire-sticker",
        flags = { "not-on-map" },

        animation = {
            filename = "__base__/graphics/entity/fire-flame/fire-flame-13.png",
            line_length = 8,
            width = 60,
            height = 118,
            frame_count = 25,
            blend_mode = "normal",
            animation_speed = 1,
            scale = 0.2,
            tint = { r = 0.5, g = 0.5, b = 0.5, a = 0.18 }, --{ r = 1, g = 1, b = 1, a = 0.35 },
            shift = math3d.vector2.mul({ -0.078125, -1.8125 }, 0.1),
            draw_as_glow = true
        },

        duration_in_ticks = 2 * defines.time.second,
        damage_per_tick = { amount = 2 / defines.time.second, type = "fire" },
        spread_fire_entity = "fire-flame-on-tree",
        fire_spread_cooldown = 30,
        fire_spread_radius = 0.75
    },
    -------- Projectile --------
    {
        type = "projectile",
        name =  MOD_NAME.."/mini-ufo-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "damage",
                        damage = { amount = 15, type = "laser" },
                        apply_damage_to_trees = true
                    },
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/mini-ufo-projectile.png",
            frame_count = 3,
            width = 32,
            height = 32,
            animation_speed = 0.4,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name = MOD_NAME.."/ufo-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = MOD_NAME.."/marspeople-explosion"
                    },
                    {
                        type = "damage",
                        damage = { amount = 15, type = "laser" },
                        apply_damage_to_trees = true
                    },
                    {
                        type = "nested-result",
                        action = {
                            type = "area",
                            force = 'not-same',
                            radius = 2,
                            ignore_collision_condition = true,
                            action_delivery = {
                                type = "instant",
                                target_effects = {
                                    type = "damage",
                                    damage = { amount = 10, type = "explosion" }
                                },
                                apply_damage_to_trees = true
                            }
                        }
                    },
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/ufo-projectile.png",
            frame_count = 1,
            width = 8,
            height = 35,
            animation_speed = 1,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name = MOD_NAME.."eye-ufo-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = MOD_NAME.."/marspeople-explosion"
                    },
                    {
                        type = "damage",
                        damage = { amount = 10, type = "electric" },
                        apply_damage_to_trees = true
                    },
                    {
                        type = "nested-result",
                        action = {
                            type = "area",
                            force = 'not-same',
                            radius = 1,
                            ignore_collision_condition = true,
                            action_delivery = {
                                type = "instant",
                                target_effects = {
                                    type = "damage",
                                    damage = { amount = 5, type = "electric" }
                                },
                                apply_damage_to_trees = true
                            }
                        }
                    },
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/eye-ufo-projectile.png",
            frame_count = 8,
            width = 32,
            height = 32,
            animation_speed = 0.5,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name =  MOD_NAME.."/daimanji-purple-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name =  MOD_NAME.."/marspeople-purple-explosion"
                    },
                    {
                        type = "damage",
                        damage = { amount = 20, type = "laser" },
                        apply_damage_to_trees = true
                    },
                    {
                        type = "nested-result",
                        action = {
                            type = "area",
                            force = 'not-same',
                            radius = 2,
                            ignore_collision_condition = true,
                            action_delivery = {
                                type = "instant",
                                target_effects = {
                                    type = "damage",
                                    damage = { amount = 10, type = "electric" }
                                },
                                apply_damage_to_trees = true
                            }
                        }
                    },
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/daimanji-purple-ball.png",
            frame_count = 12,
            width = 48,
            height = 64,
            animation_speed = 0.5,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name =  MOD_NAME.."/daimanji-thunderbolt",
        flags = { "not-on-map" },
        acceleration = 0.05,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name =  MOD_NAME.."/marspeople-thunderbolt-explosion"
                    },
                    {
                        type = "damage",
                        damage = { amount = 30, type = "electric" },
                        apply_damage_to_trees = true
                    },
                    {
                        type = "nested-result",
                        action = {
                            type = "area",
                            force = 'not-same',
                            radius = 4,
                            ignore_collision_condition = true,
                            action_delivery = {
                                type = "instant",
                                target_effects = {
                                    type = "damage",
                                    damage = { amount = 20, type = "electric" }
                                },
                                apply_damage_to_trees = true
                            }
                        }
                    },
                    {
                        type = "create-sticker",
                        sticker = "5-075-slowdown-sticker",
                        show_in_tooltip = true,
                    }
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/thunderbolt-effect.png",
            frame_count = 20,
            width = 96,
            height = 192,
            animation_speed = 0.5,
            line_length = 10,
            lines_per_file = 2,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name = MOD_NAME.."/marspeople-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        direction_only = true,
        collision_box = {{-0.5,-0.5},{0.5,0.5}},
        force_condition = "not-same",
        hit_collision_mask = {"player-layer", "train-layer","transport-belt-layer", ERMDataHelper.getFlyingLayerName()},
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name =  MOD_NAME.."/marspeople-projectile-hit"
                    },
                    {
                        type = "damage",
                        damage = { amount = 5, type = "laser" },
                        apply_damage_to_trees = true
                    },
                    {
                        type = "damage",
                        damage = { amount = 5, type = "explosion" },
                        apply_damage_to_trees = true
                    }
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/marspeople-projectile.png",
            frame_count = 12,
            width = 32,
            height = 32,
            animation_speed = 0.4,
            run_mode = "forward-then-backward",
        }
    },
    {
        type = "projectile",
        name = MOD_NAME.."/marspeople-fire-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        direction_only = true,
        collision_box = {{-0.5,-0.5},{0.5,0.5}},
        force_condition = "not-same",
        hit_collision_mask = {"player-layer", "train-layer","transport-belt-layer", ERMDataHelper.getFlyingLayerName()},
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name =  MOD_NAME.."/marspeople-projectile-hit"
                    },
                    {
                        type = "damage",
                        damage = { amount = 10, type = "explosion" },
                        apply_damage_to_trees = true
                    },
                    {
                        type = "create-fire",
                        entity_name = MOD_NAME.."/fire-flame",
                        show_in_tooltip = true,
                        initial_ground_flame_count = 2
                    },
                    {
                        type = "create-sticker",
                        sticker = MOD_NAME.."/fire-sticker",
                        show_in_tooltip = true
                    }
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/marspeople-projectile.png",
            frame_count = 12,
            width = 32,
            height = 32,
            animation_speed = 0.4,
            run_mode = "forward-then-backward",
        }
    },
    {
        type = "projectile",
        name = MOD_NAME.."/marspeople-icy-projectile",
        flags = { "not-on-map" },
        direction_only = true,
        collision_box = {{-0.5,-0.5},{0.5,0.5}},
        force_condition = "not-same",
        hit_collision_mask = {"player-layer", "train-layer", "transport-belt-layer", ERMDataHelper.getFlyingLayerName()},
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name =  MOD_NAME.."/marspeople-icy-projectile-hit"
                    },
                    {
                        type = "damage",
                        damage = { amount = 12, type = "cold" },
                        apply_damage_to_trees = true
                    },
                    {
                        type = "create-sticker",
                        sticker = "5-050-slowdown-sticker",
                        show_in_tooltip = true,
                    }
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/marspeople-icy-projectile.png",
            frame_count = 12,
            width = 32,
            height = 32,
            animation_speed = 0.4,
            run_mode = "forward-then-backward",
        }
    },
    --- Explosions
    {
        type = "explosion",
        name =  MOD_NAME.."/marspeople-projectile-hit",
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_marspeople__/graphics/entity/projectiles/marspeople-projectile-hit.png",
                width = 48,
                height = 48,
                frame_count = 12,
                animation_speed = 0.4,
                shift = util.by_pixel(0, 16),
                draw_as_glow = true,
            }
        }
    },
    {
        type = "explosion",
        name =  MOD_NAME.."/marspeople-icy-projectile-hit",
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_marspeople__/graphics/entity/projectiles/marspeople-icy-projectile-hit.png",
                width = 48,
                height = 48,
                frame_count = 12,
                animation_speed = 0.4,
                shift = util.by_pixel(0, 16),
                draw_as_glow = true,
            }
        }
    },
    {
        type = "explosion",
        name = MOD_NAME.."/marspeople-explosion",
        sound = sounds.medium_explosion(0.8),
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_marspeople__/graphics/entity/sfx/explosion.png",
                width = 96,
                height = 128,
                frame_count = 20,
                animation_speed = 0.35,
                shift = util.by_pixel(0, 16),
                draw_as_glow = true,
            }
        }
    },
    {
        type = "explosion",
        name =  MOD_NAME.."/marspeople-purple-explosion",
        flags = { "not-on-map" },
        sound = sounds.medium_explosion(0.8),
        animations = {
            {
                filename = "__erm_marspeople__/graphics/entity/sfx/purple-explosion.png",
                width = 96,
                height = 128,
                frame_count = 20,
                animation_speed = 0.35,
                shift = util.by_pixel(0, 16),
                draw_as_glow = true,
            }
        }
    },
    {
        type = "explosion",
        name =  MOD_NAME.."/marspeople-ground-explosion",
        sound = sounds.large_explosion(1.0),
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_marspeople__/graphics/entity/sfx/ground_explosion.png",
                width = 128,
                height = 192,
                frame_count = 24,
                animation_speed = 0.35,
                shift = util.by_pixel(0, 16),
                draw_as_glow = true
            }
        }
    },
    {
        type = "explosion",
        name = MOD_NAME.."/marspeople-ground-large-explosion",
        sound = sounds.large_explosion(1.0),
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_marspeople__/graphics/entity/sfx/ground_explosion.png",
                width = 128,
                height = 192,
                frame_count = 24,
                animation_speed = 0.35,
                shift = util.by_pixel(0, 16),
                draw_as_glow = true,
                scale = 1.25
            }
        }
    },
    {
        type = "explosion",
        name =  MOD_NAME.."/marspeople-thunderbolt-explosion",
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_marspeople__/graphics/entity/projectiles/thunderbolt-explosion.png",
                width = 64,
                height = 64,
                frame_count = 4,
                animation_speed = 0.35,
                shift = util.by_pixel(0, 16),
                draw_as_glow = true,
                scale = 2
            }
        }
    },
})
