---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/6/2021 2:07 PM
---

local Sprites = require('__stdlib__/stdlib/data/modules/sprites')

data:extend({
    {
        type = "projectile",
        name = "mini-ufo-projectile",
        flags = { "not-on-map" },
        acceleration = 0.005,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "damage",
                        damage = { amount = 15, type = "laser" },
                        apply_damage_to_trees = true
                    }
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/mini-ufo-projectile.png",
            frame_count = 3,
            width = 32,
            height = 32,
            priority = "high",
            animation_speed = 0.4,
            shift = util.by_pixel(0, 32),
        }
    },
    {
        type = "projectile",
        name = "marspeople-projectile",
        flags = { "not-on-map" },
        acceleration = 0.005,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "marspeople-projectile-hit"
                    },
                    {
                        type = "damage",
                        damage = { amount = 5, type = "laser" },
                        apply_damage_to_trees = true
                    },
                    {
                        type = "damage",
                        damage = { amount = 5, type = "explosion" },
                        apply_damage_to_trees = true
                    }
                }
            }
        },
        animation = {
            filename = "__erm_marspeople__/graphics/entity/projectiles/marspeople-projectile.png",
            frame_count = 12,
            width = 32,
            height = 32,
            priority = "high",
            animation_speed = 0.4,
            shift = util.by_pixel(16, 24),
            run_mode = "forward-then-backward",
        }
    },
    --- Explosions
    {
        type = "explosion",
        name = "marspeople-projectile-hit",
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_marspeople__/graphics/entity/projectiles/marspeople-projectile-hit.png",
                width = 48,
                height = 48,
                frame_count = 12,
                animation_speed = 0.4,
                shift = util.by_pixel(0, 16),
                draw_as_glow = true,
            }
        }
    },
})
