---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/28/2021 9:38 PM
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/28/2021 9:38 PM
---
require('__stdlib__/stdlib/utils/defines/time')
require('util')

local ERM_UnitHelper = require('__enemyracemanager__/lib/rig/unit_helper')
local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
local ERM_DebugHelper = require('__enemyracemanager__/lib/debug_helper')
local ERM_Config = require('__enemyracemanager__/lib/global_config')

local enemy_autoplace = require("__enemyracemanager__/lib/enemy-autoplace-utils")

local name = 'thunderbolt-turret'

-- Hitpoints

local hitpoint = 400
local max_hitpoint_multiplier = settings.startup["enemyracemanager-max-hitpoint-multipliers"].value * 1.5


-- Handles acid and poison resistance
local base_acid_resistance = 0
local incremental_acid_resistance = 75
-- Handles physical resistance
local base_physical_resistance = 0
local incremental_physical_resistance = 85
-- Handles fire and explosive resistance
local base_fire_resistance = 5
local incremental_fire_resistance = 75
-- Handles laser and electric resistance
local base_electric_resistance = 25
local incremental_electric_resistance = 55
-- Handles cold resistance
local base_cold_resistance = 15
local incremental_cold_resistance = 65

-- Handles laser damage multipliers

local base_laser_damage = 1
local incremental_laser_damage = 5

-- Handles Attack Speed

local base_attack_speed = 240
local incremental_attack_speed = 120

local collision_box = { { -0.7, -0.7 }, { 0.7, 0.7 } }
local map_generator_bounding_box = { { -2.5, -2.5 }, { 2.5, 2.5 } }
local selection_box = { { -1, -1 }, { 1, 1 } }

function ErmMarsPeople.make_thunderbolt_turret(level)
    level = level or 1
    local attack_range = ERM_UnitHelper.get_attack_range(level) + 16
    local marspeople_thunderbolt_turret = util.table.deepcopy(data.raw['electric-turret']['laser-turret'])

    -- Base changes
    marspeople_thunderbolt_turret['type'] = 'turret'
    marspeople_thunderbolt_turret['subgroup'] = 'enemies'
    marspeople_thunderbolt_turret['name'] = MOD_NAME .. '/' .. name .. '/' .. level
    marspeople_thunderbolt_turret['localised_name'] = { 'entity-name.' .. MOD_NAME .. '/' .. name, level }
    marspeople_thunderbolt_turret['flag'] = { "placeable-player", "placeable-enemy" }
    marspeople_thunderbolt_turret['max_health'] = ERM_UnitHelper.get_building_health(hitpoint, hitpoint * max_hitpoint_multiplier, level)
    marspeople_thunderbolt_turret['healing_per_tick'] = ERM_UnitHelper.get_building_healing(hitpoint, max_hitpoint_multiplier, level)
    marspeople_thunderbolt_turret['order'] = MOD_NAME .. '/' .. name .. '/'.. level
    marspeople_thunderbolt_turret['resistance'] = {
        { type = "acid", percent = ERM_UnitHelper.get_resistance(base_acid_resistance, incremental_acid_resistance, level) },
        { type = "poison", percent = ERM_UnitHelper.get_resistance(base_acid_resistance, incremental_acid_resistance, level) },
        { type = "physical", percent = ERM_UnitHelper.get_resistance(base_physical_resistance, incremental_physical_resistance, level) },
        { type = "fire", percent = ERM_UnitHelper.get_resistance(base_fire_resistance, incremental_fire_resistance, level) },
        { type = "explosion", percent = ERM_UnitHelper.get_resistance(base_fire_resistance, incremental_fire_resistance, level) },
        { type = "laser", percent = ERM_UnitHelper.get_resistance(base_electric_resistance, incremental_electric_resistance, level) },
        { type = "electric", percent = ERM_UnitHelper.get_resistance(base_electric_resistance, incremental_electric_resistance, level) },
        { type = "cold", percent = ERM_UnitHelper.get_resistance(base_cold_resistance, incremental_cold_resistance, level) }
    }
    marspeople_thunderbolt_turret['map_color'] = ERM_UnitHelper.format_map_color(settings.startup['erm_marspeople-map-color'].value)
    marspeople_thunderbolt_turret['collision_box'] = collision_box
    marspeople_thunderbolt_turret['selection_box'] = selection_box
    marspeople_thunderbolt_turret['map_generator_bounding_box'] = map_generator_bounding_box
    marspeople_thunderbolt_turret['autoplace'] = enemy_autoplace.enemy_worm_autoplace(0, FORCE_NAME)
    marspeople_thunderbolt_turret['call_for_help_radius'] = 50
    marspeople_thunderbolt_turret['spawn_decorations_on_expansion'] = false
    marspeople_thunderbolt_turret['energy_source'] = nil

    -- Attack Changes
    marspeople_thunderbolt_turret['attack_parameters']['ammo_category'] = "marspeople-damage"
    marspeople_thunderbolt_turret['attack_parameters']['cooldown'] = ERM_UnitHelper.get_attack_speed(base_attack_speed, incremental_attack_speed, level)
    marspeople_thunderbolt_turret['attack_parameters']['cooldown_deviation'] = 0.1
    marspeople_thunderbolt_turret['attack_parameters']['range'] = attack_range
    marspeople_thunderbolt_turret['attack_parameters']['damage_modifier'] = ERM_UnitHelper.get_damage(base_laser_damage, incremental_laser_damage, level)

    marspeople_thunderbolt_turret['attack_parameters']['ammo_type'] = {
        category = "marspeople-damage",
        action = {
            type = "direct",
            action_delivery = {
                type = "projectile",
                projectile = MOD_NAME.."/daimanji-thunderbolt",
                starting_speed = 0.5,
                max_range = ERM_Config.get_max_projectile_range(),
            }
        }
    }
    marspeople_thunderbolt_turret.corpse = 'marspeople-thunderbolt-turret-remnants'
    -- Animation Changes
    ERM_UnitTint.mask_tint(marspeople_thunderbolt_turret['folded_animation']['layers'][3], ERM_UnitTint.tint_purple())
    ERM_UnitTint.mask_tint(marspeople_thunderbolt_turret['preparing_animation']['layers'][3], ERM_UnitTint.tint_purple())
    ERM_UnitTint.mask_tint(marspeople_thunderbolt_turret['prepared_animation']['layers'][3], ERM_UnitTint.tint_purple())
    ERM_UnitTint.mask_tint(marspeople_thunderbolt_turret['folding_animation']['layers'][2], ERM_UnitTint.tint_purple())

    local marspeople_thunderbolt_turret_remants = util.table.deepcopy(data.raw['corpse']['laser-turret-remnants'])
    marspeople_thunderbolt_turret_remants.name = 'marspeople-thunderbolt-turret-remnants'
    ERM_UnitTint.mask_tint(marspeople_thunderbolt_turret_remants['animation'][1]['layers'][2], ERM_UnitTint.tint_purple())
    ERM_UnitTint.mask_tint(marspeople_thunderbolt_turret_remants['animation'][2]['layers'][2], ERM_UnitTint.tint_purple())
    ERM_UnitTint.mask_tint(marspeople_thunderbolt_turret_remants['animation'][3]['layers'][2], ERM_UnitTint.tint_purple())

    data:extend({
        marspeople_thunderbolt_turret_remants,
        marspeople_thunderbolt_turret
    })
end
